name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.ref }}
      - name: Publish
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: publishPlugin
        env:
          INTELLIJ_TOKEN: ${{ secrets.INTELLIJ_TOKEN }}
