name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3.14.2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          ref: ${{ github.ref }}
      - name: Publish
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: publishPlugin
        env:
          INTELLIJ_TOKEN: ${{ secrets.INTELLIJ_TOKEN }}
